-- AlterTable
ALTER TABLE `employees` ADD COLUMN `motDePasse` VARCHAR(255) NULL,
    ADD COLUMN `roleUtilisateur` ENUM('SUPER_ADMIN', 'ADMIN_ENTREPRISE', 'CAISSIER', 'EMPLOYE') NULL DEFAULT 'EMPLOYE';
