-- AlterTable
ALTER TABLE `dashboards` MODIFY `roleRequis` ENUM('SUPER_ADMIN', 'ADMIN_ENTREPRISE', 'CAISSIER', 'VIGILE', 'EMPLOYE') NOT NULL DEFAULT 'EMPLOYE';

-- AlterTable
ALTER TABLE `employees` MODIFY `roleUtilisateur` ENUM('SUPER_ADMIN', 'ADMIN_ENTREPRISE', 'CAISSIER', 'VIGILE', 'EMPLOYE') NULL DEFAULT 'EMPLOYE';

-- AlterTable
ALTER TABLE `users` MODIFY `role` ENUM('SUPER_ADMIN', 'ADMIN_ENTREPRISE', 'CAISSIER', 'VIGILE', 'EMPLOYE') NOT NULL DEFAULT 'EMPLOYE';
